import fitz  # PyMuPDF
from fpdf import FPDF
import re
from datetime import datetime

def extract_text_from_pdf(uploaded_file) -> str:
    """Extract clean text from an uploaded PDF file."""
    try:
        uploaded_file.seek(0)
        doc = fitz.open(stream=uploaded_file.read(), filetype="pdf")
        text = ""
        for page in doc:
            text += page.get_text() + "\n\n"
        doc.close()
        return text.strip()
    except Exception as e:
        return f"Error extracting text from PDF: {str(e)}"


def markdown_to_plain(text: str) -> str:
    """Simple markdown cleaner for PDF generation."""
    text = re.sub(r'^#+\s*', '', text, flags=re.MULTILINE)  # headers
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)             # bold
    text = re.sub(r'\*(.*?)\*', r'\1', text)                 # italic
    text = re.sub(r'`(.*?)`', r'\1', text)                   # code
    text = re.sub(r'^\s*[-*+]\s+', '• ', text, flags=re.MULTILINE)  # bullets
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


class ResumePDF(FPDF):
    def header(self):
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by JobFit AI • {datetime.now().strftime("%d %b %Y")}', align='C')


def create_pdf_from_text(content: str, title: str = "Document") -> bytes:
    """
    Convert plain/markdown text into a clean professional PDF.
    Returns PDF as bytes.
    """
    pdf = ResumePDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_margins(18, 18, 18)

    # Title
    pdf.set_font('Helvetica', 'B', 16)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, title, ln=True, align='C')
    pdf.ln(6)

    # Body
    clean = markdown_to_plain(content)
    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(40, 40, 40)

    for line in clean.split('\n'):
        line = line.strip()
        if not line:
            pdf.ln(4)
            continue

        # Simple heading detection
        if line.isupper() and len(line) < 60:
            pdf.set_font('Helvetica', 'B', 12)
            pdf.ln(3)
            pdf.multi_cell(0, 7, line)
            pdf.set_font('Helvetica', '', 11)
        else:
            pdf.multi_cell(0, 6.5, line)

    return bytes(pdf.output())
